package xyz.heavenlydev.p256account

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import xyz.heavenlydev.p256account.account.Call
import xyz.heavenlydev.p256account.action.AaveV3
import xyz.heavenlydev.p256account.action.Erc20
import xyz.heavenlydev.p256account.action.Erc721
import xyz.heavenlydev.p256account.action.Native
import xyz.heavenlydev.p256account.action.UniswapV2
import xyz.heavenlydev.p256account.action.Weth
import xyz.heavenlydev.p256account.crypto.Numeric
import java.io.File
import java.math.BigInteger

/**
 * Milestone 4 — every action template must reproduce the golden vector in
 * `sdk/actions.golden.json`, which is generated by foundry's `cast`
 * (`sdk/tooling/scripts/gen-actions-golden.sh`) and shares no code with this
 * SDK. The iOS (`ActionsInteropTests.swift`) and TypeScript
 * (`actions.test.ts`) suites assert against the same file, so agreement
 * between the three SDKs is anchored to an external ABI encoder rather than to
 * each other.
 */
class ActionsInteropTest {

    private val golden: JSONObject = loadGolden()
    private val fx: JSONObject = golden.getJSONObject("fixtures")

    private fun addr(key: String) = fx.getString(key)
    private fun num(key: String) = BigInteger(fx.getString(key))

    /** Every template, built with the fixture values, keyed by golden id. */
    private fun built(): Map<String, Call> {
        val alice = addr("alice"); val bob = addr("bob")
        val token = addr("token"); val token2 = addr("token2")
        val router = addr("router"); val pool = addr("pool")
        val nft = addr("nft"); val weth = addr("weth")
        val amount = num("amount"); val amountMin = num("amountMin")
        val wei = num("wei"); val tokenId = num("tokenId")
        val deadline = num("deadline"); val variable = num("interestRateModeVariable")

        return mapOf(
            "native.transfer" to Native.transfer(bob, wei),

            "erc20.transfer" to Erc20.transfer(token, bob, amount),
            "erc20.approve" to Erc20.approve(token, router, amount),
            "erc20.transferFrom" to Erc20.transferFrom(token, alice, bob, amount),

            "erc721.safeTransferFrom" to Erc721.safeTransferFrom(nft, alice, bob, tokenId),
            "erc721.approve" to Erc721.approve(nft, bob, tokenId),
            "erc721.setApprovalForAll" to Erc721.setApprovalForAll(nft, bob, true),

            "weth.deposit" to Weth.deposit(weth, wei),
            "weth.withdraw" to Weth.withdraw(weth, amount),

            "univ2.swapExactTokensForTokens" to UniswapV2.swapExactTokensForTokens(
                router, amount, amountMin, listOf(token, token2), alice, deadline,
            ),
            "univ2.swapExactETHForTokens" to UniswapV2.swapExactETHForTokens(
                router, wei, amountMin, listOf(weth, token), alice, deadline,
            ),
            "univ2.swapExactTokensForETH" to UniswapV2.swapExactTokensForETH(
                router, amount, amountMin, listOf(token, weth), alice, deadline,
            ),

            "aave.supply" to AaveV3.supply(pool, token, amount, alice),
            "aave.borrow" to AaveV3.borrow(pool, token, amount, variable, alice),
            "aave.repay" to AaveV3.repay(pool, token, amount, variable, alice),
            "aave.withdraw" to AaveV3.withdraw(pool, token, amount, alice),
        )
    }

    @Test fun everyTemplateMatchesItsCastGeneratedGolden() {
        val built = built()
        val templates = golden.getJSONArray("templates")
        assertTrue("golden file has no templates", templates.length() > 0)

        for (i in 0 until templates.length()) {
            val g = templates.getJSONObject(i)
            val id = g.getString("id")
            val call = built[id] ?: throw AssertionError("no Kotlin template for golden '$id'")

            assertEquals("$id: target address", g.getString("to").lowercase(), call.to.lowercase())
            assertEquals("$id: call value", BigInteger(g.getString("value")), call.value)
            assertEquals("$id: calldata", g.getString("data").lowercase(), Numeric.bytesToHex(call.data).lowercase())
        }
    }

    @Test fun everyKotlinTemplateIsCoveredByAGolden() {
        val templates = golden.getJSONArray("templates")
        val ids = (0 until templates.length()).map { templates.getJSONObject(it).getString("id") }.toSet()
        val uncovered = built().keys.filterNot { it in ids }
        assertEquals("templates missing from actions.golden.json", emptyList<String>(), uncovered)
    }

    @Test fun payableTemplatesCarryValueAndOthersDoNot() {
        // A template that silently dropped `value` would still encode correctly
        // and only fail on-chain, so pin the payable set explicitly.
        val payable = setOf("native.transfer", "weth.deposit", "univ2.swapExactETHForTokens")
        for ((id, call) in built()) {
            if (id in payable) {
                assertTrue("$id must carry ETH value", call.value > BigInteger.ZERO)
            } else {
                assertEquals("$id must not carry ETH value", BigInteger.ZERO, call.value)
            }
        }
    }

    @Test fun executeBatchCalldataMatchesCastGolden() {
        // `bytes[]` is doubly dynamic and hand-rolled in every SDK. Pin it
        // against cast rather than trusting three implementations to agree.
        val batches = golden.optJSONArray("batch") ?: return
        for (i in 0 until batches.length()) {
            val b = batches.getJSONObject(i)
            val tos = b.getJSONArray("to").let { a -> (0 until a.length()).map { a.getString(it) } }
            val values = b.getJSONArray("value").let { a -> (0 until a.length()).map { BigInteger(a.getString(it)) } }
            val datas = b.getJSONArray("calldata").let { a ->
                (0 until a.length()).map { Numeric.hexToBytes(a.getString(it)) }
            }
            val nonce = BigInteger(b.getString("nonce"))
            val signature = Numeric.hexToBytes(b.getString("signature"))

            val encoded = xyz.heavenlydev.p256account.abi.Abi.encodeWithSelector(
                "executeBatch(address[],uint256[],bytes[],uint256,bytes)",
                listOf(
                    xyz.heavenlydev.p256account.abi.AbiValue.AddressArray(tos),
                    xyz.heavenlydev.p256account.abi.AbiValue.UintArray(values),
                    xyz.heavenlydev.p256account.abi.AbiValue.BytesArray(datas),
                    xyz.heavenlydev.p256account.abi.AbiValue.Uint(nonce),
                    xyz.heavenlydev.p256account.abi.AbiValue.DynBytes(signature),
                ),
            )
            assertEquals(
                "batch ${b.getString("id")}: encoded calldata",
                b.getString("encoded").lowercase(),
                Numeric.bytesToHex(encoded).lowercase(),
            )

            // The DIGEST is what the signature actually covers. Pinning only the
            // calldata would let batchDigest drift silently.
            val calls = tos.indices.map { Call(to = tos[it], value = values[it], data = datas[it]) }
            val digest = xyz.heavenlydev.p256account.eip712.Eip712.batchDigest(
                b.getString("chainId").toLong(), b.getString("account"), calls, nonce,
            )
            assertEquals(
                "batch ${b.getString("id")}: EIP-712 digest",
                b.getString("digest").lowercase(),
                Numeric.bytesToHex(digest).lowercase(),
            )
        }
    }

    @Test fun personalSignDigestMatchesCastGolden() {
        // The EIP-1271 wrapper. The golden deliberately wraps an Execute digest
        // — the exact value an attacker would present as a "login challenge" —
        // so this pins the case the wrapper exists for.
        val entries = golden.optJSONArray("personalSign") ?: return
        for (i in 0 until entries.length()) {
            val e = entries.getJSONObject(i)
            val hashHex = e.getString("hash")
            val got = xyz.heavenlydev.p256account.eip712.Eip712.personalSignDigest(
                e.getString("chainId").toLong(),
                e.getString("account"),
                Numeric.hexToBytes(hashHex),
            )
            val gotHex = Numeric.bytesToHex(got).lowercase()
            assertEquals("personalSign digest", e.getString("digest").lowercase(), gotHex)
            assertTrue(
                "the 1271 path must not return the raw hash — that is the exploit",
                gotHex != hashHex.lowercase(),
            )
        }
    }

    @Test fun batchLimitMatchesTheContract() {
        // The golden generator reads MAX_BATCH_CALLS straight out of lib.rs, so
        // this catches the SDK constant drifting away from the contract.
        val limits = golden.optJSONObject("limits") ?: return
        assertEquals(
            "MAX_BATCH_CALLS must match the contract",
            limits.getInt("maxBatchCalls"),
            xyz.heavenlydev.p256account.account.MAX_BATCH_CALLS,
        )
    }

    @Test fun nativeTransferHasNoCalldata() {
        val call = Native.transfer(addr("bob"), num("wei"))
        assertEquals(0, call.data.size)
    }

    /**
     * Walk up from the working directory to find `sdk/actions.golden.json`.
     * Gradle runs unit tests with cwd = the module directory, but IDE runners
     * vary, so resolve by search rather than a fixed relative path.
     */
    private fun loadGolden(): JSONObject {
        var dir: File? = File(System.getProperty("user.dir") ?: ".").absoluteFile
        while (dir != null) {
            val candidate = File(dir, "actions.golden.json")
            if (candidate.isFile) return JSONObject(candidate.readText())
            dir = dir.parentFile
        }
        throw IllegalStateException(
            "actions.golden.json not found above ${System.getProperty("user.dir")}; " +
                "run sdk/tooling/scripts/gen-actions-golden.sh",
        )
    }
}
